<?php

include 'passwordStrength.php';

$session=false;
if(isset($_SESSION['name'])!=""){
    $session=true;
}

include("../template/dbConnection.php");

$conn=connect();
$sql = "SELECT * FROM Utenti";
$result = mysqli_query($conn, $sql);

// define variables and set to empty values
$emailErr = $pswdErr = "";
$email = $pswd = "";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
	
    $error=false;
  
    if (empty($_POST["email"])) {
        $emailErr = "Inserire una email valida";
	    $error=true;
    } else {
        $email = test_input($conn, $_POST["email"]);
        // check if e-mail address is well-formed
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $emailErr = "Inserire una password valida"; 
            $error=true;
        }
	   if(!$error){
            while($row = $result->fetch_assoc()){
                if($email==$row["Email"]){
                    $emailErr = "Utente già registrato"; 
                    $error=true;
                    break;
                }		
            }
        }
    }
    
    $passwordLength = 2;
    
    if (empty($_POST["pwd"])) {
        $pswdErr = "Inserire la password";
	    $error=true;
    } else if (!password_strength($_POST["pwd"], $passwordLength)){
        $pswdErr = "Password poco sicura";
	    $error=true;
    } else {
        $pswd = $_POST["pwd"];
        $hash = password_hash($pswd, PASSWORD_DEFAULT); //a random salt will be generated by default
    }  

    if(!$error){
        $conn=connect();
	    $sql = "insert into Utenti (Email, Password)
		values ('".$email."', '".$hash."');";
	
        mysqli_query($conn,$sql);	
	
	    $_SESSION['name'] = $email;
	
	    $_POST = array();
        
	    header('Location: '.$_SERVER['REQUEST_URI']);
    } 
  
  }
mysqli_close($conn);


 function test_input($con, $data) {
    $data = trim($data); //The trim() function removes whitespace and other predefined characters from both sides of a string.
    $data = stripslashes($data); //The stripslashes() function removes backslashes added by the addslashes() function.
    $data = htmlspecialchars($data); //The htmlspecialchars() function converts some predefined characters to HTML entities.
    $data = mysqli_real_escape_string($con, $data); //Escapes special characters in a string for use in a SQL statement, taking into account the current charset of the connection
    return $data;
}

?>